version: '3.8'

services:
  app:
    container_name: proxy-entrypoint-service
    build: .
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
      - DATASOURCE_USER=${POSTGRES_USER:-postgres}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-root}
      - DATASOURCE_URL=jdbc:postgresql://proxy_entrypoint_db:5432/${POSTGRES_DB:-aass}
    ports:
      - ${PORT_EXPOSE:-8080}:8080
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: proxy_entrypoint_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aass}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    ports:
      - ${POSTGRES_PORT_EXPOSE:-5432}:5432
    volumes:
      - aass_db_data:/var/lib/postgresql/data

volumes:
  aass_db_data:
    name: aass_db_data

networks:
  default:
    name: aass_network
    external: true
