services:

  # ENTRYPOINT API SERVICE
  app:
    container_name: proxy-entrypoint-service
    build:
      context: ../proxy_entrypoint_service
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - DATASOURCE_USER=${POSTGRES_USER:-postgres}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-root}
      - DATASOURCE_URL=jdbc:postgresql://proxy_entrypoint_db:5432/${POSTGRES_DB:-aass}
      - PREDICT_SERVICE_URI=${PREDICT_SERVICE_URI:-http://predict_service:8000}
      - NER_SERVICE_URI=${NER_SERVICE_URI:-http://ner_service:8000}
      - DL_SERVICE_URI=${DL_SERVICE_URI:-http://dl_service:8000}
    ports:
      - ${ENTRYPOINT_PORT_EXPOSE:-8080}:8080
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: proxy_entrypoint_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aass}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    ports:
      - ${POSTGRES_PORT_EXPOSE:-5432}:5432
    volumes:
      - aass_db_data:/var/lib/postgresql/data

  # PY AI SERVICES
  predict_service:
    container_name: predict_service
    build:
      context: ../predict_service
      dockerfile: Dockerfile
    ports:
      - ${PREDICT_SERVICE_PORT_EXPOSE:-8010}:8000
    env_file:
      - .predict_env
    volumes:
      - ../predict_service:/workspace

  ner_service:
    container_name: ner_service
    build:
      context: ../ner_service
      dockerfile: Dockerfile
    ports:
      - ${NER_SERVICE_PORT_EXPOSE:-8011}:8000
    env_file:
      - .ner_env
    volumes:
      - ../ner_service:/workspace

  dl_service:
    container_name: dl_service
    build:
      context: ../dl_service
      dockerfile: Dockerfile
    ports:
      - ${DL_SERVICE_PORT_EXPOSE:-8012}:8000
    volumes:
      - ../dl_service:/workspace

  # FRONTEND
  web:
    container_name: natdis-detect-fe
    build:
      context: ../../natdis-detect-fe/natdis
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Bratislava
      - API_HOST=${DJANGO_API_HOST:-http://proxy-entrypoint-service:8080}
      - KEYCLOAK_AUTH_URL=${KEYCLOAK_AUTH_URL}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_GRANT_TYPE=${KEYCLOAK_GRANT_TYPE}
    ports:
      - ${DJANGO_PORT_EXPOSE:-8180}:8000
    volumes:
      - "../../natdis-detect-fe/natdis/dcesm:/code/dcesm"

  # CAMUNDA
  camunda:
    container_name: natdis-camunda
    image: camunda/camunda-bpm-platform:run-latest
    ports:
      - ${CAMUNDA_PORT_EXPOSE:-8081}:8080

volumes:
  aass_db_data:
    name: aass_db_data
  aass_camunda_data:
    name: aass_camunda_data

networks:
  default:
    name: aass_network
    external: true
